### ISSUE TITLE
Update-connection

### ISSUE THREAD

**Issue by timwilsonpremier** [Microsoft/PowerBI-Cli#20] opened 2016-07-20 13:40 UTC
Hi,

I am getting error 'Error updating connection string' 'parameters[valueElement] must be of type object.

What am I doing wrong?

syntax powerbi update-connection -w [workspaceid] -d [datasetid] -s "connectionstring" -u [user] -p [pass]

Thanks

**Comment by wbreza** [comment] 2016-07-20 17:16
Thanks @timwilsonpremier.  We will investigate and get back to you soon.

**Comment by wbreza** [comment] 2016-07-20 19:52
Root issue is in the `powerbi-node` package.  Created [issue](https://github.com/Microsoft/PowerBI-Node/issues/15) to track a fix.

Will keep this open till the root issue is resolved.

**Comment by wbreza** [comment] 2016-07-22 20:04
The root cause has been resolved in `powerbi-node` and new package has been published with the updated version dependency. 

v1.0.2

**Closed by wbreza** 2016-07-22 20:04 UTC
Labels: bug
